apiVersion: v1
data:
  prometheus-additional.yaml: LSBqb2JfbmFtZTogJ2JsYWNrYm94LXBpbmcnCiAgc2NyYXBlX2ludGVydmFsOiAxNXMKICBtZXRyaWNzX3BhdGg6IC9wcm9iZQogIHBhcmFtczoKICAgIG1vZHVsZTogW2ljbXBdCiAgc3RhdGljX2NvbmZpZ3M6CiAgLSB0YXJnZXRzOiBbIjEwLjAuMi4xNzIiXQogIHJlbGFiZWxfY29uZmlnczoKICAtIHNvdXJjZV9sYWJlbHM6IFtfX2FkZHJlc3NfX10KICAgIHRhcmdldF9sYWJlbDogX19wYXJhbV90YXJnZXQKICAtIHNvdXJjZV9sYWJlbHM6IFtfX3BhcmFtX3RhcmdldF0KICAgIHRhcmdldF9sYWJlbDogaW5zdGFuY2UgIAogIC0gdGFyZ2V0X2xhYmVsOiBfX2FkZHJlc3NfXwogICAgcmVwbGFjZW1lbnQ6IGJsYWNrYm94LWV4cG9ydGVyLXByb21ldGhldXMtYmxhY2tib3gtZXhwb3J0ZXI6OTExNSAgIyBUaGlzIGlzIHlvdXIgYmxhY2tib3gtZXhwb3J0ZXIgc2VydmljZQ==
kind: Secret
metadata:
  creationTimestamp: null
  name: additional-scrape-configs
  namespace: monitoring
