- job_name: 'blackbox-ping'
  scrape_interval: 15s
  metrics_path: /probe
  params:
    module: [icmp]
  static_configs:
  - targets: ["10.0.2.193"]
  relabel_configs:
  - source_labels: [__address__]
    target_label: __param_target
  - source_labels: [__param_target]
    target_label: instance  
  - target_label: __address__
    replacement: blackbox-exporter-prometheus-blackbox-exporter:9115  # This is your blackbox-exporter service