apiVersion: v1
kind: Service
metadata:
 name: appsvc2
 namespace: default
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector: #quem vai fazer q se conecte o service ao deployment, que tiver este selector app1
    app: app2
