apiVersion: v1
kind: Service
metadata:
 name: appsvc1
 namespace: default
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: {{ .Values.service.nodePort }}
  selector: #quem vai fazer q se conecte o service ao deployment, que tiver este selector app1
    app: app1
