name: gitops
on:
  push:
    branches: 
      - dev
      - master
      - 'feature/*'
      - 'hotfix/*'
      - 'release/v[0-9].[0-9]+.[0-9]+'
      - 'v[0-9].[0-9]+.[0-9]+'
    tags:
      - 'v[0-9].[0-9]+.[0-9]+'
  pull_request:
    branches:
      - dev
      - master

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps: 
      - name: checkout
        uses: actions/checkout@v3


  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    
    steps:  
      - name: commit
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Danilo
          author_email: danilogo0001@gmail.com
          message: GitOps
          add: '*'
          cwd: '/home/mibre/terraform/aws/eks/terraform-aws-eks-prometheus-grafana-blackbox'

        #run: |
        #  git config --local user.email "danilogo0001@gmail.com"
        #  git config --local user.name "Danilo"
        #  git commit -am "GitOps"

      #- name: push
      #  uses: ad-m/github-push-action@master

      - name: update app2
        run: |
          cd apps
          kubectl apply -f app2.yaml

  